#! /bin/sh
### BEGIN INIT INFO
# Provides:          doorman
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Set up the doorman
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting doorman"

		python /home/pi/doorman/main.py

    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping doorman"

		# TODO

    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/doorman {start|stop}"
    exit 1
    ;;
esac
